Components/BasketSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission9_zm275.Models;
namespace Mission9_zm275.Components
{
    public class BasketSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public BasketSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
    
}

Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission9_zm275.Models;

namespace Mission9_zm275.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }
        public TypesViewComponent(IBookstoreRepository temp)
        {
           repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTypes = RouteData?.Values["projectType"];

            var types = repo.Book.Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }

    
}

Views/Shared/Summary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Books

 
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Author</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">Category: @Model.Category</div>
    <p>ISBN: @Model.Isbn</p>
    <p>Publisher: @Model.Publisher</p>
    <p>Page Count: @Model.PageCount</p>
    <p>Price: @Model.Price</p>

    <form method="post" asp-page="/Purchase" >
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end breadcrumb">Add to Cart</button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission9_zm275</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap-grid.css" integrity="sha512-PvqHJhhotDCbhn+7kfLEQeUcmrdWywRieVodtlA6rYfyuU9q8Y4mFe7IaQpO5DuGW20DLXewo6GVWc0rGCidQg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Book Store</span>
        <vc:basket-summary />
        <span><a asp-controller="Home" asp-action="Index">Home</a></span>
    </div>
    
    
    <div class="row m-1 p-1 rounded-top">
        <div id="categories" class="col-2">
            <vc:types></vc:types>

        </div>

        <div class="col-sm-10">
            @RenderBody()
        </div>
    </div>
</body>
</html>