Controllers/PurchasesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission9_zm275.Models;

namespace Mission9_zm275.Controllers
{
    public class PurchasesController : Controller
    {
        private IPurchasesRepository repo { get; set; }
        private Basket basket { get; set; }
        public PurchasesController(IPurchasesRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }
        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }
            if (ModelState.IsValid){
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View(); 
            }
        }
    }
}

Views/Purchases/Checkout.cshtml
@{
}

@model Purchase

<h2>Check out now</h2>

<p>Enter details below:</p>

<form method="post" asp-controller="Purchases" asp-action="Checkout">

    <div asp-validation-summary="All" class="text-danger"></div>
    <h4>Ship To</h4>

    <div class="form-group">
        <label asp-for="Name">Name</label><input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine1">Address Line 1:</label><input asp-for="AddressLine1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine2">Address Line 2:</label><input asp-for="AddressLine2" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine3">Address Line 3:</label><input asp-for="AddressLine3" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="City">City:</label><input asp-for="City" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="State">State:</label><input asp-for="State" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Zip">Zip:</label><input asp-for="Zip" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Country">Country:</label><input asp-for="Country" class="form-control" />
    </div>
    <div class="checkbox">
        <label>
            <input asp-for="Anonymous" /> Donate Anonymously</label>
    </div>
    <div class="float-end">
        <input type="submit" class="btn-primary" value="Submit Purchase Order" />
    </div>
</form>